"use client";

import "../../public/css/theme-default.css";
import "../../public/css/bootstrap.min.css";
import "../../public/css/owl.carousel.min.css";
import "../../public/css/nivo-slider.css";
import "../../public/css/animate.css";
import "../../public/css/animated-text.css";
import "../../public/fonts/font-awesome/css/font-awesome.min.css";
import "../../public/css/flaticon.css";
import "../../public/css/meanmenu.min.css";
import "../../public/css/style.css";
import "../../public/css/owl.transitions.css";
import "../../public/venobox/venobox.css";
import "../../public/css/responsive.css";
import "../../public/css/widget.css";
import "../../public/css/external.css";
import "../../public/css/main.css";
import "../../public/css/bootstrap-icons.min.css";
import "../../public/boxicons/css/boxicons.min.css";
import "../../public/remixicon/remixicon.css";
import header from "./_Common/_Header/Header";
// import "./globals.css";
import footer from "./_Common/_Footer/Footer";
import Script from "next/script";
import { Suspense } from "react";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Header from "./_Common/_Header/Header";

// export const metadata: Metadata = {
//   title: "Manuscript-Edit",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Manuscript-Edit</title>
      <link href="/img/manu.ico" rel="icon"></link>
      <Script type="text/javascript" src="/admin/admin/js/vendor/jquery-3.2.1.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/bootstrap.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/bootstrap.bundle.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/owl.carousel.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/jquery.counterup.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/waypoints.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/wow.js" />
      <Script type="text/javascript" src="/admin/admin/js/imagesloaded.pkgd.min.js" />
      {/* <Script type='text/javascript' src="/venobox/venobox.js"/> */}
      <Script type="text/javascript" src="/admin/admin/js/ajax-mail.js" />
      <Script type="text/javascript" src="/admin/admin/js/testimonial.js" />
      <Script type="text/javascript" src="/admin/admin/js/animated-text.js" />
      <Script type="text/javascript" src="/admin/admin/venobox/venobox.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/isotope.pkgd.min.js" />
      <Script type="text/javascript" src="/admin/admin/js/jquery.nivo.slider.pack.js" />
      <Script type="text/javascript" src="/admin/admin/js/jquery.meanmenu.js" />
      <Script type="text/javascript" src="/admin/admin/js/jquery.scrollUp.js" />
      <Script type="text/javascript" src="/admin/admin/js/theme.js" />
      <body className="loaded">
        <ToastContainer />
        {/* <header/> */}
        {/* {header()} */}
        <Header />
        <Suspense fallback={<p>Loading feed...</p>}>
          {children}
        </Suspense>
        {footer()}
      </body>
    </html>
  );
}
